version: "3.8"

services:
  postgres:
    container_name: gerenciamento_estoque-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gerenciamento_estoque
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
  redis:
    image: redis:alpine
    container_name: gerenciamento_estoque-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
